name: Pull Request Checker

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '!.github/workflows/**'

jobs:
  build:
    name: Pull request check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.1'
      - name: Prepare Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          java-package: jdk
          distribution: 'temurin'
          cache: 'gradle'
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps
      - name: Cache Gradle Build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-core-${{ github.sha }}
          restore-keys: |
            gradle-builds
      - name: Build with Gradle
        run: |
          ./gradlew :app:assembleDebug
          ./gradlew :app:assembleRelease
          ./gradlew :demo-app:assembleDebug
          ./gradlew :demo-app:assembleRelease
          echo "MODULE_DEBUG_APK_FILE=$(find app/build/outputs/apk/debug -name '*.apk')" >> $GITHUB_ENV
          echo "DEMO_DEBUG_APK_FILE=$(find demo-app/build/outputs/apk/debug -name '*.apk')" >> $GITHUB_ENV
          echo "MODULE_RELEASE_APK_FILE=$(find app/build/outputs/apk/release -name '*.apk')" >> $GITHUB_ENV
          echo "DEMO_RELEASE_APK_FILE=$(find demo-app/build/outputs/apk/release -name '*.apk')" >> $GITHUB_ENV
      - name: Upload Artifacts(module-debug)
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.MODULE_DEBUG_APK_FILE }}
          name: module-debug
      - name: Upload Artifacts(demo-debug)
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.DEMO_DEBUG_APK_FILE }}
          name: demo-debug
      - name: Upload Artifacts(module-release)
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.MODULE_RELEASE_APK_FILE }}
          name: module-release
      - name: Upload Artifacts(demo-release)
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.DEMO_RELEASE_APK_FILE }}
          name: demo-release
